config:
  validation: true
  warningsAsErrors: false

complexity:
  LongParameterList:
    allowedFunctionParameters: 8
    ignoreDefaultParameters: true

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  InjectDispatcher:
    active: true
  RedundantSuspendModifier:
    active: true
  SleepInsteadOfDelay:
    active: true
  SuspendFunSwallowedCancellation:
    active: true
  SuspendFunWithFlowReturnType:
    active: true

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable

style:
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  UnusedPrivateFunction:
    ignoreAnnotated:
      - Preview

ktlint:
  active: true
  code_style: android_studio
